#	$OpenBSD: Makefile,v 1.6 1996/09/15 16:50:34 michaels Exp $
#	@(#)Makefile	8.1 (Berkeley) 6/6/93

PROG=	locate.bigram
NOMAN=	noman
BINDIR=	${LIBEXECDIR}
CFLAGS+= -I${.CURDIR}/../locate

include ${.TOPDIR}/usr.bin/locate/Makefile.inc
include ${.TOPDIR}/mk/bsd.prog.mk
