#	$OpenBSD: Makefile,v 1.4 2017/07/09 21:23:19 espie Exp $

VPATH+=	${.CURDIR}/..

PROG=	lesskey
SRCS=	lesskey.c version.c

BINDIR=	/usr/bin

CFLAGS+=-I${.CURDIR}/..

include ${.TOPDIR}/mk/bsd.prog.mk
