SUBDIR=	apply banner cal calendar cmp compress ctags \
	diff diff3 doas encrypt find less mail mg patch \
	sdiff sed shar signify spell uudecode uuencode \
	vis what which xargs yacc xinstall
include ${.TOPDIR}/mk/bsd.subdir.mk
