#SUBDIR=	apply awk banner cal calendar cmp compress ctags \
#	diff diff3 doas encrypt find less lex locate m4 mail \
#	mg patch sdiff sed shar signify spell uudecode uuencode \
#	vis what which xargs yacc
SUBDIR=	apply awk banner cal cmp ctags \
	diff diff3 doas encrypt find less lex locate m4 mail \
	mg patch sdiff sed shar signify spell uudecode uuencode \
	vis what which xargs yacc
include ${.TOPDIR}/mk/bsd.subdir.mk
