#	$OpenBSD: Makefile,v 1.6 1996/09/15 16:50:36 michaels Exp $
#	@(#)Makefile	8.1 (Berkeley) 6/6/93

PROG=	locate.code
CFLAGS+=-I${.CURDIR}/../locate 
NOMAN=	noman
BINDIR=	${LIBEXECDIR}

include ${.TOPDIR}/usr.bin/locate/Makefile.inc
include ${.TOPDIR}/mk/bsd.prog.mk
